# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: My Blog
description: > # this means to ignore newlines until "baseurl:"
  Go go go!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.example.com" # the base hostname & protocol for your site
twitter_username: me

plugins:
  - jekyll-archives
  - jekyll-paginate
  - rouge
  - jekyll-sitemap

name: My Blog
default_author: John Doe

# Build settings
markdown: kramdown
permalink: /:year/:month/:title.html
paginate: 10
excerpt_separator: <!--more-->
highlighter: rouge

jekyll-archives:
  enabled:
    - categories
    - year
    - month
  layouts: 
    year: archive-year
    month: archive-month
    category: archive-category
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    category: '/:name/'

exclude: [Gemfile, Gemfile.lock]

